### ISSUE TITLE
USER STORY: Create user account page

### ISSUE THREAD

**Issue by RobTheThief** [RobTheThief/steelworks-ci-5#10]
As a **user** I can **go to my account page** so that **look at and edit my details**

## Acceptance Criteria

- Acceptance Criteria 1: There must be an account page with the user details
- Acceptance Criteria 2: There must be the ability to edit user details.
- Acceptance Criteria 3: There must be the ability to view current plan and update plan.

## Tasks

- [x] Task 1: Create the main page and add the sections
- [x] Task 2: Create requests to access information about products, instructors, user details, classes.
- [x] Task 3: Create requests to edit information about products, instructors, user details, classes.
