### ISSUE TITLE
USER STORY: Cretae log out functionality

### ISSUE THREAD

**Issue by RobTheThief** [RobTheThief/steelworks-ci-5#11]
As a **user** I can **logout** so that **I can keep my personal information and account secure**

## Acceptance Criteria

- Acceptance Criteria 1: There must a logout button in a drop down by the user icon in the navbar.
- Acceptance Criteria 2: When the logout button is clicked the user must be logged out and need to enter username and password again to access account.

## Tasks

- [x] Task 1: Create an auth request to logout.
- [x] Task 2: Add the request function to a button in a drop down by the user icon.
- [x] Task 3: Try to use a MUI component for the dropdown.
