### ISSUE TITLE
USER STORY: Refactor and clean up any unsed code

### ISSUE THREAD

**Issue by RobTheThief** [RobTheThief/steelworks-ci-5#13]
As a **developer** I can **refactor my code base** so that **it is more maintainable**

## Acceptance Criteria

- Acceptance Criteria 1: There should not be repeated code where possible.
- Acceptance Criteria 2: There should not be any unused code.
- Acceptance Criteria 3: Variable and function names should be descriptive and appropriate.

## Tasks

- [x] Task 1: Look for repeated code that can be refactored to one function or variable.
- [x] Task 2: Remove any unused code or endpoints.
- [x] Task 3: Check function and variable names are descriptive and appropriate.
