### ISSUE TITLE
USER STORY: Set up authentication and permissions on endpoints

### ISSUE THREAD

**Issue by RobTheThief** [RobTheThief/steelworks-ci-5#14]
As a **User** I can **register and login** so that **I can access the data that I need and know that others cannot**

## Acceptance Criteria

- Acceptance Criteria 1: Permissions and authentication should be set for request.
- Acceptance Criteria 2: Sensitive user data should not be accessibly unless logged in.
- Acceptance Criteria 3: The user should have access to all functions and data that they need to login, register and update subscriptions or user details.

## Tasks

- [x] Task 1: Set permissions for each endpoint in the backend.
- [x] Task 2: Set authentication for each endpoint in the backend.
- [x] Task 3: Test that user has all necessary access and cannot access sensitive data unless logged in.
