### ISSUE TITLE
USER STORY: Make sure each page has a head with meta data.

### ISSUE THREAD

**Issue by RobTheThief** [RobTheThief/steelworks-ci-5#15]
As a **user** I can **easily search for this gym on Google** so that **I can easily discover it or find it when I need it**

## Acceptance Criteria

- Acceptance Criteria 1: There should  be a head for each page.
- Acceptance Criteria 2: The head should have have a title and meta tags

## Tasks

- [x] Task 1: Add the helmet component to each page.
- [x] Task 2: Add a title to each page.
- [x] Task 3: Add meta tags to each page.
