### ISSUE TITLE
USER STORY: improve contact section appearance.

### ISSUE THREAD

**Issue by RobTheThief** [RobTheThief/steelworks-ci-5#18]
As a **user** I can **can easily use the contact section** so that **I can contact the gym**

## Acceptance Criteria

- Acceptance Criteria 1: The contact section layout should be evenly spaced.
- Acceptance Criteria 2: This section layout should have easily readable text.
- Acceptance Criteria 3: It should open a new tab on submit.

## Tasks

- [x] Task 1: Fix margin spacing and text size.
- [x] Task 2: Fix text colour contrast.
- [x] Task 3: Set to open new tab on submit.
