### ISSUE TITLE
Set up the project environment

### ISSUE THREAD

**Issue by RobTheThief** [RobTheThief/steelworks-ci-5#2]
As a **developer** I can **set up the project environment** so that **begin development**

## Acceptance Criteria  
- Acceptance Criteria 1: The front end and back end should be set up and running
- Acceptance Criteria 2: I should be able to run locally the front end in development mode while being served locally from the back end in development mode.
- Acceptance Criteria 3: The data base should be set up locally and I should be able to make queries from the back end.   
## Tasks  
- [x] Task1:  Install the necessary Python and Javascript packages.
- [x] Task2:  Write a catchall view that proxies requests for index.html to the React development server
- [x] Task3: Set up a postgreql database locally for development and connect it up to the backend.
