### ISSUE TITLE
USER STORY: Begin development on the front end and build out the home page and navigation

### ISSUE THREAD

**Issue by RobTheThief** [RobTheThief/steelworks-ci-5#5]
As a **User** I can **go to the home page** so that **I can see information about the the gym and what they have to offer**

## Acceptance Criteria

- Acceptance Criteria 1: There should be a hero image and a main heading with the gym name.
- Acceptance Criteria 2: There should be navigation to browse the other pages of the website when they are available.
- Acceptance Criteria 3: There should be an about section.
- Acceptance Criteria 4: There should be a price plans section.
- Acceptance Criteria 5: There should be a contact section.

## Tasks

- [x] Task 1: Install react router for page navigation.
- [x] Task 2: Install TailwindCSS for component styling.
- [x] Task 3: Investigate if Material UI can be used for navigation and buttons and install if required.
- [x] Task 4: Create a layout for the navigation.
- [x] Task 5: Create components for navigation.
- [x] Task 6: Create hero, about, price plan and contact sections.
