### ISSUE TITLE
USER STORY: Create the login and register page.

### ISSUE THREAD

**Issue by RobTheThief** [RobTheThief/steelworks-ci-5#6]
As a **User** I can **go to the login and register page** so that **login or create an account**

## Acceptance Criteria

- Acceptance Criteria 1: There should be a page for login and register accessible from the navbar.
- Acceptance Criteria 2: There should be a form for login and for register.
- Acceptance Criteria 3: By default the register form will display with a link to the login section.
- Acceptance Criteria 4: There should be a link from the login section to the register section.

## Tasks

- [x] Task 1: Create a page for login and register.
- [x] Task 2: Use react router to create a link from the navbar to the login and register page.
- [x] Task 3: Create a component for register and one for login.
- [x] Task 4: Add a link from each component to the other
