### ISSUE TITLE
USER STORY: Add login and register functionality.

### ISSUE THREAD

**Issue by RobTheThief** [RobTheThief/steelworks-ci-5#9]
As a **User** I can **create an account and login** so that **buy a gym membership**

## Acceptance Criteria

- Acceptance Criteria 1: There should be a login and register page with a form for each use.
- Acceptance Criteria 2: There should be form validation to prevent submitting the wrong type of info.
- Acceptance Criteria 3: There should be error messages if incorrect info submitted.
- Acceptance Criteria 4: The user name should be displayed in the navigation bar.

## Tasks

- [x] Task 1: Create a fetch request for each login and register and add to form.
- [x] Task 2: Create a helper function to get cookies.
- [x] Task 3: Add form validation through using the form element and in the register/login functions.
- [x] Task 4: Create error messages and a modal to display them.
- [x] Task 5: Create a function to check the user profile once logged in and display the user name in the navbar.
